In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

In [3]:
# **1.	读取数据新闻.xlsx(3分)
data = pd.read_excel("新闻.xlsx")
titles = data["标题"]
data

关键词                                  标题  \
0    华能信托                  信托公司2019年上半年经营业绩概览   
1    华能信托                        首单信托型企业ABS获批   
2    华能信托             华能贵诚信托孙磊:金融科技助力打造开放信托生态   
3    华能信托        华能贵诚信托孙磊:金融科技已经成为信托行业重要的基础设施   
4    华能信托            格力电器股权转让意向方闭门开会 华能信托赫然在列   
..    ...                                 ...   
957    京东  2019京东手机金机奖大众投票开启:5G前夜,用户青睐什么样的手机?   
958    京东    2019京东手机金机奖评选火热进行中,快来看看你的机型入选了吗?   
959    京东             德国大闸蟹泛滥成灾 其实他们可以找京东生鲜合作   
960    京东    德国吸尘器大牌Fakir费卡伊尔登陆京东 除尘电器领域新势力来袭   
961    京东        京东、百度加入收费阵营 信用卡还款是否还有“免费午餐”?   

                                                    网址       来源  \
0    http://www.financialnews.com.cn/jrsb_m/xt/zx/2...  中国金融新闻网   
1       http://www.jjckb.cn/2018-10/23/c_137552198.htm    经济参考网   
2    https://baijiahao.baidu.com/s?id=1639276579449...    同花顺财经   
3         https://finance.qq.com/a/20190716/007898.htm     腾讯财经   
4    https://finance.sina.com.cn/trust/roll/2019-05...       新浪   
..                                                 ...      ...   
957  https://baijiahao.baidu.com/s?id=1641113457834...     驱动中国   
958  https://baijiahao.baidu.com/s?id=1641112511125...      泡泡网   
959  https://tech.china.com/article/20190806/kejiyu...      中华网   
960  https://baijiahao.baidu.com/s?id=1641111090707...    爆料大重庆   
961         https://www.jrtzb.com.cn/text.asp?i=217564    金融投资网   

                    时间  
0    2019年07月23日 00:00  
1    2018年10月23日 12:21  
2    2019年07月17日 10:49  
3    2019年07月16日 18:53  
4    2019年05月22日 22:53  
..                 ...  
957  2019年08月06日 18:35  
958  2019年08月06日 18:20  
959  2019年08月06日 18:00  
960  2019年08月06日 17:58  
961  2019年08月06日 17:55  

[962 rows x 5 columns]

In [12]:
# **2.	遍历来进行所有标题的分词(3分)
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(max_df=1.0, min_df=1, max_features=None)
X = vectorizer.fit_transform(titles)
for name in vectorizer.get_feature_names_out():
    print(name)

00700
03亿
08s特别版京东众筹中
0业务模式升级拉开序幕
0建设
10
100
100万个工作岗位
10个python简单技巧
12
1660ti
17名责任人将
18亿元估值合理
1亿元
2000多名体育爱好者共享
2016年中国打响了人工智能发展的发令枪
2018年上半年62家信托公司净利润排名
2018年信托业人均创利304万元
2019
2019chinajoy圆满收官
2019china北京人工智能识别与控制展示会官网
2019世界人工智能大会倒计时30天
2019世界人工智能大会助力打造人工智能
2019丨itheat热点科技展台人气火爆
2019中国医疗人工智能市场研究报告
2019京东手机金机奖大众投票开启
2019京东手机金机奖评选火热进行中
2019人工智能与教育大数据峰会在京开幕
2019人工智能与教育大数据峰会开幕
2019唐恩科技四大行业解决方案惊艳亮相
2019年上海人工智能大会将于8月23日在上海举办
2019年人工智能市场规模将近280
2019年人工智能市场规模将近280亿元
2019年体育传统项目学校总决赛录取中长跑项目成绩偏差引起的思考
2019年到期债务达590亿
2019年度上海市科技小巨人企业
2019成落地之年
2019福布斯2000强
2019科技创新融合峰会进入倒计时
2019重庆青少年体育夏令营关心关爱留守儿童
2019首届明德儒商论坛聚焦中国智慧
2021年开始
2021年起广州中考体育分值升至70分
2022年体育消费总规模达2800亿元
28日下午文章马伊琍官宣离婚
2k屏麒麟980顶配加持
2亿
30年崛起之路
360看中的是彩生活的社区服务模式
37万粉求她退娱乐圈
4000万人种下情侣树
421文档究竟是怎么回事
47亿入股后欲追投百亿
4个月学完
4英寸成了全家人的娱乐神器
5000mah
50w闪充
50亿爆雷
53
54
58家信托上半年净利排位
5g
5g前夜
5g将为人工智能带来全新动能
5g时代人工智能将重塑世界
5亿元
600万人绑定淘宝亲情号
70年数据说明什么
7499元
75倍
7知其然知其所以然
82亿元
8月1日晚间公告集锦
8月8日
8月8日厦门市体育中心场馆免费开放
8月8日宜昌36个体育场馆免费开放
8月8日沪近千处公共体育场馆和设施免费开放
8月底揭晓
8月起停

In [13]:
# **3.	展示前三条新闻的分词结果(3分)
row = X.toarray()[:3]
for i in row:
    print(vectorizer.get_feature_names_out()[i.ravel().nonzero()[0]])

['信托公司2019年上半年经营业绩概览']
['首单信托型企业abs获批']
['华能贵诚信托孙磊' '金融科技助力打造开放信托生态']


In [16]:
# **4.	建立词频矩阵(3分)
print(X.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [17]:
# **5.	查看词袋和对应的顺序(3分)
vectorizer.get_feature_names_out()

array(['00700', '03亿', '08s特别版京东众筹中', ..., '黑客都用python', '黑科技', '鼻祖'],
      dtype=object)

In [25]:
# **6.	将之前所有的新闻标题进行文本向量化(3分)
X = vectorizer.fit_transform(titles)
X

<962x2015 sparse matrix of type '<class 'numpy.int64'>'
	with 2427 stored elements in Compressed Sparse Row format>

In [19]:
# **7.	查看所有新闻标题的词袋(3分)
vectorizer.get_feature_names_out()

array(['00700', '03亿', '08s特别版京东众筹中', ..., '黑客都用python', '黑科技', '鼻祖'],
      dtype=object)

In [27]:
# **8.	文本向量化(3分)
X = vectorizer.fit_transform(titles)
X

<962x2015 sparse matrix of type '<class 'numpy.int64'>'
	with 2427 stored elements in Compressed Sparse Row format>

In [28]:
# **9.	查看词袋的第一种方式(3分)
vectorizer.get_feature_names_out()


array(['00700', '03亿', '08s特别版京东众筹中', ..., '黑客都用python', '黑科技', '鼻祖'],
      dtype=object)

In [30]:
# **10.	查看词袋的第二种方式(3分)
print(X.toarray()[:3])

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [34]:
# **11.	将之前所有的新闻标题进行文本向量化并通过pandas展示(3分)
data = pd.DataFrame(X.toarray(),columns=vectorizer.get_feature_names_out())
data

00700  03亿  08s特别版京东众筹中  0业务模式升级拉开序幕  0建设  10  100  100万个工作岗位  \
0        0    0            0            0    0   0    0          0   
1        0    0            0            0    0   0    0          0   
2        0    0            0            0    0   0    0          0   
3        0    0            0            0    0   0    0          0   
4        0    0            0            0    0   0    0          0   
..     ...  ...          ...          ...  ...  ..  ...        ...   
957      0    0            0            0    0   0    0          0   
958      0    0            0            0    0   0    0          0   
959      0    0            0            0    0   0    0          0   
960      0    0            0            0    0   0    0          0   
961      0    0            0            0    0   0    0          0   

     10个python简单技巧  12  ...  高质量办好民族体育盛会  高通纷纷屈服  高通骁龙开启数字娱乐新篇章  鲜花分分钟送达  \
0                0   0  ...            0       0              0        0   
1                0   0  ...            0       0              0        0   
2                0   0  ...            0       0              0        0   
3                0   0  ...            0       0              0        0   
4                0   0  ...            0       0              0        0   
..             ...  ..  ...          ...     ...            ...      ...   
957              0   0  ...            0       0              0        0   
958              0   0  ...            0       0              0        0   
959              0   0  ...            0       0              0        0   
960              0   0  ...            0       0              0        0   
961              0   0  ...            0       0              0        0   

     麦积山石窟  麦锐娱乐否认倒闭传闻  黄釉瓷器众筹爆红京东  黑客都用python  黑科技  鼻祖  
0        0           0           0           0    0   0  
1        0           0           0           0    0   0  
2        0           0           0           0    0   0  
3        0           0           0           0    0   0  
4        0           0           0           0    0   0  
..     ...         ...         ...         ...  ...  ..  
957      0           0           0           0    0   0  
958      0           0           0           0    0   0  
959      0           0           0           0    0   0  
960      0           0           0           0    0   0  
961      0           0           0           0    0   0  

[962 rows x 2015 columns]

In [35]:
# **12.	自主选择算法进行聚类分群(6分)
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=2,  init='k-means++',max_iter=300)
kmeans.fit(X)
kmeans.labels_
# **13.	把数字1改成其他数字看看效果(3分

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [37]:
# **13.	把数字1改成其他数字看看效果(3分
kmeans = KMeans(n_clusters=4,  init='k-means++',max_iter=300)
kmeans.fit(X)
kmeans.labels_


array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,